Repository browsermt/bergamot-translator, pull requests merged in 2021-04, with the labels that each got.

#86 Make AlignedMemory the means of passing in memory
  app/bergamot-translator-app-bytearray.cpp
  src/TranslationModel.h
  src/translator/TranslationModel.cpp
  src/translator/service.h
Labels: unified-api

#79 Removes vocabs and propogates fixes for breaks
  app/marian-decoder-new.cpp
  src/translator/response.cpp
  src/translator/response.h
  src/translator/service.h
Labels: cleanup, marian

#85 Strengthen the Annotation class: Handle empty sentences and tests
  src/tests/annotation_tests.cpp
  src/translator/sentence_ranges.cpp
  src/translator/sentence_ranges.h
Labels: high-priority, marian

#80 Cleanup API: Refactor request on-complete transition
  app/service-cli-bytearray.cpp
  app/service-cli.cpp
  src/translator/CMakeLists.txt
  src/translator/TranslationModel.cpp
  src/translator/batch_translator.cpp
  src/translator/request.cpp
  src/translator/request.h
  src/translator/response.cpp
  src/translator/response.h
  src/translator/response_builder.cpp
  src/translator/response_builder.h
  src/translator/response_options.h
  src/translator/sentence_ranges.cpp
  src/translator/sentence_ranges.h
  src/translator/service.cpp
  src/translator/service.h
Labels: marian
